import { ArabicLetter } from '../types';

export const arabicLetters: ArabicLetter[] = [
  { char: 'أ', name: 'همزة', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ب', name: 'باء', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ت', name: 'تاء', ghahr: 'همس', strength: 'شدة' },
  { char: 'ث', name: 'ثاء', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'ج', name: 'جيم', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ح', name: 'حاء', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'خ', name: 'خاء', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'د', name: 'دال', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ذ', name: 'ذال', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'ر', name: 'راء', ghahr: 'جهر', strength: 'بينية' },
  { char: 'ز', name: 'زاي', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'س', name: 'سين', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'ش', name: 'شين', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'ص', name: 'صاد', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'ض', name: 'ضاد', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'ط', name: 'طاء', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ظ', name: 'ظاء', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'ع', name: 'عين', ghahr: 'جهر', strength: 'بينية' },
  { char: 'غ', name: 'غين', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'ف', name: 'فاء', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'ق', name: 'قاف', ghahr: 'جهر', strength: 'شدة' },
  { char: 'ك', name: 'كاف', ghahr: 'همس', strength: 'شدة' },
  { char: 'ل', name: 'لام', ghahr: 'جهر', strength: 'بينية' },
  { char: 'م', name: 'ميم', ghahr: 'جهر', strength: 'بينية' },
  { char: 'ن', name: 'نون', ghahr: 'جهر', strength: 'بينية' },
  { char: 'هـ', name: 'هاء', ghahr: 'همس', strength: 'رخاوة' },
  { char: 'و', name: 'واو', ghahr: 'جهر', strength: 'رخاوة' },
  { char: 'ي', name: 'ياء', ghahr: 'جهر', strength: 'رخاوة' },
];